# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      24.1.0
# Date created:         Tue Feb 20 22:15:05 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_Create an AWS Lambda Function using S3 zip file.yaml
