# Exported from:        http://MarioMijicsiPad:5516/
# Release version:      23.1.0
# Date created:         Mon Oct 09 16:22:38 CEST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: f1
spec:
- name: jenkins_server
  type: jenkins.Server
  url: localhost:8080
