# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      24.1.0
# Date created:         Tue Feb 20 17:36:34 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_Delete Application in ArgoCD.yaml
  - Workflow_Install Argo Rollouts.yaml
  - Workflow_Install ArgoCD.yaml
  - Workflow_Setup ArgoCD application with initial deployment.yaml
