# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      23.1.0
# Date created:         Wed Sep 27 11:02:01 CEST 2023

---
apiVersion: xl-release/v1
kind: Import
metadata:
  home: i
spec:
  imports:
  - I/love/mango/Releasefile.yaml
---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  home: i
spec:
- directory: love
  teams:
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#create_release_other_folder
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#edit_security
    - template#create_release
    - template#edit_triggers
    - template#edit_precondition
    - template#edit_failure_handler
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - workflow#view_execution
    - release#advance_task_transition
    - workflow#abort_execution
    - release#edit_security
    - release#restart_phase
    - release#lock_task
    - folder#view
    - release#edit_task_script
    - release#edit_task_flag
    - release#edit_task_configuration_facet
    - release#edit_task_dates
    - workflow#start_execution
    - release#edit_task
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - release#abort
