# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      23.1.0
# Date created:         Wed Sep 27 15:53:15 CEST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: i
spec:
- directory: I
  children:
  - directory: love
    children:
    - template: love_Temp
      scheduledStartDate: 2023-09-27T09:00:00+02:00
      phases:
      - phase: New Phase
      riskProfile: Default risk profile
      author: admin
      defaultTargetFolder: ./love
