# Exported from:        http://MarioMijicsiPad:5516/
# Release version:      23.1.0
# Date created:         Thu Mar 21 16:20:53 CET 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: grandparent/parent/child
spec:
- template: c3
  scheduledStartDate: 2024-03-21T09:00:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: "333"
      type: xlrelease.Task
  riskProfile: Default risk profile
