# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      23.1.0
# Date created:         Fri Jan 05 14:44:46 CET 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: E1
spec:
- directory: e2
  children:
  - directory: e3
