# Exported from:        http://MarioMijicsiPad:5516/
# Release version:      24.1.0-SNAPSHOT
# Date created:         Mon Feb 19 15:51:15 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Workflow_Delete Application in ArgoCD.yaml
  - Workflow_Install Argo Rollouts.yaml
  - Workflow_Install ArgoCD.yaml
  - Workflow_Setup ArgoCD application with initial deployment.yaml
