# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      24.1.0-SNAPSHOT
# Date created:         Tue Feb 20 17:21:07 CET 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: ArgoCD
spec:
- template: Delete Application in ArgoCD
  scheduledStartDate: 2023-04-27T15:00:00+02:00
  dueDate: 2023-04-27T16:00:00+02:00
  phases:
  - phase: Delete Application in ArgoCD
    tasks:
    - name: Application Details
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      variables:
      - projectDetails
      - argoCDApiServer
      - Application_name
    - name: Delete Application in ArgoCD
      type: argocd.RemoveApplication
      variableMapping:
        argoServer: "${argoCDApiServer}"
      capabilities:
      - remote
      applicationName: "${Application_name}"
    - name: Delete Application in Release
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
    color: '#3d6c9e'
  kind: WORKFLOW
  categories:
  - Application onboarding
  variables:
  - type: xlrelease.StringVariable
    key: Application_name
    showOnReleaseStart: false
    label: Application Name
    description: Application name to delete from ArgoCD
  - type: xlrelease.StringVariable
    key: projectDetails
    showOnReleaseStart: false
    label: Project Details
    description: Name of the project in ArgoCD where the Application is mapped to
    value: default
  - type: xlrelease.ReferenceVariable
    key: argoCDApiServer
    showOnReleaseStart: false
    label: ArgoCD API server
    description: ArgoCD Api Server connection details
    referencedType: argocd.APIServer
  disableNotifications: true
  scriptUsername: admin
  author: Digital.ai
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/png
    file: !file "template-logo/01d81f95a92b5ebbae77081f9988c520aa79d73e/argo-icon.png"
  defaultTargetFolder: Digital.ai - Official/Workflow Executions
