# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      24.1.0
# Date created:         Fri Apr 12 14:49:53 CEST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
