# Exported from:        http://MarioMijicsiPad:5516/
# Release version:      23.1.0
# Date created:         Mon Mar 25 16:29:28 CET 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: testin
spec:
- template: test-template
  scheduledStartDate: 2024-03-25T09:00:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: "1243"
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
