# Exported from:        http://MarioMijicsiPad:5516/
# Release version:      23.1.0
# Date created:         Thu Mar 21 11:03:02 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
