# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      24.1.0
# Date created:         Wed Apr 10 13:38:56 CEST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: var-map
spec:
- template: dijete
  scheduledStartDate: 2024-04-10T09:00:00+02:00
  phases:
  - phase: New Phase
    tasks:
    - name: print valyoohs
      type: xlrelease.ScriptTask
      script: |-
        print ${text-var}
        print ${bool-var}
        print ${list-var}
    color: '#3d6c9e'
  variables:
  - type: xlrelease.StringVariable
    key: list-var
    label: list-var
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - "1"
      - "2"
      - "3"
  - type: xlrelease.StringVariable
    key: bool-var
    label: Script
    description: Script
  - type: xlrelease.StringVariable
    key: text-var
    label: Script
    description: Script
  riskProfile: Default risk profile
  author: admin
- template: roditelj
  scheduledStartDate: 2024-04-10T09:00:00+02:00
  phases:
  - phase: New Phase
    tasks:
    - name: enter-values
      type: xlrelease.UserInputTask
      owner: admin
      variables:
      - bool-var
      - text-var
      - parent-list
    - name: dfgf
      type: xlrelease.CreateReleaseTask
      variableMapping:
        templateVariables[0].value: "${parent-list}"
      newReleaseTitle: some-title
      templateVariables:
      - type: xlrelease.StringVariable
        key: list-var
        label: list-var
      - type: xlrelease.StringVariable
        key: bool-var
        label: Script
        description: Script
        value: "1"
      - type: xlrelease.StringVariable
        key: text-var
        label: Script
        description: Script
        value: "1"
      template: ./dijete
  variables:
  - type: xlrelease.StringVariable
    key: parent-list
    requiresValue: false
    showOnReleaseStart: false
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - "1"
      - "2"
      - "3"
  - type: xlrelease.StringVariable
    key: text-var
    requiresValue: false
    showOnReleaseStart: false
    label: text-var
  - type: xlrelease.BooleanVariable
    key: bool-var
    requiresValue: false
    showOnReleaseStart: false
    label: bool-var
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_roditelj_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
