# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      24.1.0
# Date created:         Tue Feb 20 17:42:27 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
