# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      23.1.0
# Date created:         Tue Jan 23 16:00:35 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
