# Exported from:        http://MarioMijicsiPad:5516/
# Release version:      23.1.0
# Date created:         Thu Jan 25 15:50:26 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
