# Exported from:        http://MarioMijicsiPad:5516/
# Release version:      23.1.0
# Date created:         Thu Sep 28 13:12:32 CEST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: lubenica
spec:
- pattern: lubenica_pattern
  stages:
  - stage: asdg
  - stage: sdg
- directory: kostica
