# Exported from:        http://Darkos-MBP.home:5516/
# Release version:      23.1.0
# Date created:         Thu Mar 14 09:18:55 CET 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_ccc.yaml
